/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as PredicationsRouteImport } from './routes/predications'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LivreRouteImport } from './routes/livre'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaiementSuccessRouteImport } from './routes/paiement.success'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const PredicationsRoute = PredicationsRouteImport.update({
  id: '/predications',
  path: '/predications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreRoute = LivreRouteImport.update({
  id: '/livre',
  path: '/livre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementSuccessRoute = PaiementSuccessRouteImport.update({
  id: '/paiement/success',
  path: '/paiement/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/contact': typeof ContactRoute
  '/livre': typeof LivreRoute
  '/notes': typeof NotesRoute
  '/predications': typeof PredicationsRoute
  '/programme': typeof ProgrammeRoute
  '/ressources': typeof RessourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/paiement/success': typeof PaiementSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/contact': typeof ContactRoute
  '/livre': typeof LivreRoute
  '/notes': typeof NotesRoute
  '/predications': typeof PredicationsRoute
  '/programme': typeof ProgrammeRoute
  '/ressources': typeof RessourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/paiement/success': typeof PaiementSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/contact': typeof ContactRoute
  '/livre': typeof LivreRoute
  '/notes': typeof NotesRoute
  '/predications': typeof PredicationsRoute
  '/programme': typeof ProgrammeRoute
  '/ressources': typeof RessourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/paiement/success': typeof PaiementSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/agenda'
    | '/contact'
    | '/livre'
    | '/notes'
    | '/predications'
    | '/programme'
    | '/ressources'
    | '/sitemap.xml'
    | '/paiement/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/agenda'
    | '/contact'
    | '/livre'
    | '/notes'
    | '/predications'
    | '/programme'
    | '/ressources'
    | '/sitemap.xml'
    | '/paiement/success'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/agenda'
    | '/contact'
    | '/livre'
    | '/notes'
    | '/predications'
    | '/programme'
    | '/ressources'
    | '/sitemap.xml'
    | '/paiement/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  ContactRoute: typeof ContactRoute
  LivreRoute: typeof LivreRoute
  NotesRoute: typeof NotesRoute
  PredicationsRoute: typeof PredicationsRoute
  ProgrammeRoute: typeof ProgrammeRoute
  RessourcesRoute: typeof RessourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PaiementSuccessRoute: typeof PaiementSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predications': {
      id: '/predications'
      path: '/predications'
      fullPath: '/predications'
      preLoaderRoute: typeof PredicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livre': {
      id: '/livre'
      path: '/livre'
      fullPath: '/livre'
      preLoaderRoute: typeof LivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement/success': {
      id: '/paiement/success'
      path: '/paiement/success'
      fullPath: '/paiement/success'
      preLoaderRoute: typeof PaiementSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  ContactRoute: ContactRoute,
  LivreRoute: LivreRoute,
  NotesRoute: NotesRoute,
  PredicationsRoute: PredicationsRoute,
  ProgrammeRoute: ProgrammeRoute,
  RessourcesRoute: RessourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PaiementSuccessRoute: PaiementSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
